//export const dynamic = "force-dynamic"; // defaults to auto

export async function GET(request) {
  const data = {
    wants: "https://api.mathtrade.com.ar/media/wants/wants_SEmNMKs.txt",
    results: "https://api.mathtrade.com.ar/media/results/res.txt",
    items_count: 6502,
    games_count: 2746,
    users_count: 533,
    item_trades: 2313,
    users_trading: 422,
    locations: [
      {
        location: {
          id: 1,
          name: "AMBA",
          province: "AMBA",
          geolocation: null,
          mandatory_attendance: true,
        },
        items_count: 3594,
        games_count: 1628,
        users_count: 259,
      },
      {
        location: {
          id: 4,
          name: "Rosario",
          province: "Santa Fe",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 222,
        games_count: 83,
        users_count: 27,
      },
      {
        location: {
          id: 34,
          name: "Bahía Blanca",
          province: "Buenos Aires",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 306,
        games_count: 110,
        users_count: 30,
      },
      {
        location: {
          id: 41,
          name: "Resistencia",
          province: "Chaco",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 59,
        games_count: 18,
        users_count: 8,
      },
      {
        location: {
          id: 32,
          name: "Trelew",
          province: "Chubut",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 37,
        games_count: 24,
        users_count: 2,
      },
      {
        location: {
          id: 2,
          name: "Mendoza",
          province: "Mendoza",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 431,
        games_count: 156,
        users_count: 29,
      },
      {
        location: {
          id: 9,
          name: "Rafaela",
          province: "Santa Fe",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 118,
        games_count: 54,
        users_count: 7,
      },
      {
        location: {
          id: 12,
          name: "Neuquén",
          province: "Neuquén",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 218,
        games_count: 87,
        users_count: 18,
      },
      {
        location: {
          id: 35,
          name: "Santa Rosa",
          province: "La Pampa",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 51,
        games_count: 25,
        users_count: 7,
      },
      {
        location: {
          id: 10,
          name: "Salta",
          province: "Salta",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 211,
        games_count: 96,
        users_count: 17,
      },
      {
        location: {
          id: 8,
          name: "Mar del Plata",
          province: "Buenos Aires",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 124,
        games_count: 59,
        users_count: 11,
      },
      {
        location: {
          id: 26,
          name: "La Plata",
          province: "Buenos Aires",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 103,
        games_count: 43,
        users_count: 16,
      },
      {
        location: {
          id: 6,
          name: "Colón",
          province: "Entre Ríos",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 92,
        games_count: 36,
        users_count: 6,
      },
      {
        location: {
          id: 30,
          name: "San Juan",
          province: "San Juan",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 55,
        games_count: 26,
        users_count: 8,
      },
      {
        location: {
          id: 19,
          name: "Villa María",
          province: "Córdoba",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 37,
        games_count: 10,
        users_count: 7,
      },
      {
        location: {
          id: 36,
          name: "Paso de los Libres",
          province: "Corrientes",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 10,
        games_count: 9,
        users_count: 1,
      },
      {
        location: {
          id: 29,
          name: "San Carlos de Bariloche",
          province: "Río Negro",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 31,
        games_count: 13,
        users_count: 4,
      },
      {
        location: {
          id: 27,
          name: "Puerto Madryn",
          province: "Chubut",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 10,
        games_count: 3,
        users_count: 2,
      },
      {
        location: {
          id: 3,
          name: "Córdoba",
          province: "Córdoba",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 309,
        games_count: 104,
        users_count: 29,
      },
      {
        location: {
          id: 44,
          name: "Necochea",
          province: "Buenos Aires",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 7,
        games_count: 5,
        users_count: 1,
      },
      {
        location: {
          id: 13,
          name: "Paraná",
          province: "Entre Ríos",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 71,
        games_count: 26,
        users_count: 8,
      },
      {
        location: {
          id: 33,
          name: "Santa Fe",
          province: "Santa Fe",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 47,
        games_count: 20,
        users_count: 6,
      },
      {
        location: {
          id: 31,
          name: "San Luis",
          province: "San Luis",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 19,
        games_count: 4,
        users_count: 1,
      },
      {
        location: {
          id: 25,
          name: "Gualeguaychú",
          province: "Entre Ríos",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 103,
        games_count: 28,
        users_count: 5,
      },
      {
        location: {
          id: 7,
          name: "San Miguel de Tucumán",
          province: "Tucumán",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 65,
        games_count: 32,
        users_count: 3,
      },
      {
        location: {
          id: 17,
          name: "Esperanza",
          province: "Santa Fe",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 43,
        games_count: 11,
        users_count: 5,
      },
      {
        location: {
          id: 42,
          name: "Posadas",
          province: "Misiones",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 15,
        games_count: 8,
        users_count: 2,
      },
      {
        location: {
          id: 24,
          name: "Comodoro Rivadavia",
          province: "Chubut",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 9,
        games_count: 4,
        users_count: 2,
      },
      {
        location: {
          id: 39,
          name: "Junín",
          province: "Buenos Aires",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 1,
        games_count: 0,
        users_count: 1,
      },
      {
        location: {
          id: 21,
          name: "Catamarca",
          province: "Catamarca",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 31,
        games_count: 7,
        users_count: 2,
      },
      {
        location: {
          id: 14,
          name: "Santiago del Estero",
          province: "Santiago del Estero",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 1,
        games_count: 1,
        users_count: 1,
      },
      {
        location: {
          id: 16,
          name: "San Nicolás",
          province: "Buenos Aires",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 20,
        games_count: 4,
        users_count: 2,
      },
      {
        location: {
          id: 22,
          name: "Chascomús",
          province: "Buenos Aires",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 10,
        games_count: 1,
        users_count: 1,
      },
      {
        location: {
          id: 43,
          name: "Venado Tuerto",
          province: "Santa Fe",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 13,
        games_count: 5,
        users_count: 4,
      },
      {
        location: {
          id: 5,
          name: "San Salvador de Jujuy",
          province: "Jujuy",
          geolocation: null,
          mandatory_attendance: false,
        },
        items_count: 29,
        games_count: 6,
        users_count: 1,
      },
    ],
    segments: [
      {
        item_segment: "01-10",
        users_count: 288,
      },
      {
        item_segment: "11-20",
        users_count: 117,
      },
      {
        item_segment: "21-30",
        users_count: 41,
      },
      {
        item_segment: "31-40",
        users_count: 22,
      },
      {
        item_segment: "41-50",
        users_count: 12,
      },
      {
        item_segment: "51+",
        users_count: 10,
      },
      {
        item_segment: "0",
        users_count: 43,
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    status: 200,
    "Content-Type": "application/json",
  });
}
