// export const dynamic = "force-dynamic"; // defaults to auto

export async function GET(request) {
  const data = [
    {
      id: 1,
      name: "AMBA",
      province: "AMBA",
      geolocation: null,
      mandatory_attendance: true,
      referral: {
        email: "email@email.com",
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
      },
    },
    {
      id: 34,
      name: "Bahía Blanca",
      province: "Buenos Aires",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 98,
        username: "damianyaz",
        first_name: "Damian",
        last_name: "Yazyi",
        email: "email@email.com",
        location: 34,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id145874.jpg",
      },
    },
    {
      id: 22,
      name: "Chascomús",
      province: "Buenos Aires",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 45,
        username: "megonzalez9881",
        first_name: "Maria Elisa",
        last_name: "Gonzalez",
        email: "email@email.com",
        location: 22,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id162711.jpg",
      },
    },
    {
      id: 39,
      name: "Junín",
      province: "Buenos Aires",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 39,
        username: "sebman",
        first_name: "Sebastian",
        last_name: "Bronfen",
        email: "email@email.com",
        location: 39,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: null,
      },
    },
    {
      id: 26,
      name: "La Plata",
      province: "Buenos Aires",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 179,
        username: "lovelypao27",
        first_name: "Paola",
        last_name: "Alonso",
        email: "email@email.com",
        location: 26,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 8,
      name: "Mar del Plata",
      province: "Buenos Aires",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 20,
        username: "suarezmn",
        first_name: "Maximiliano",
        last_name: "Suárez",
        email: "email@email.com",
        location: 8,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id194505.jpg",
      },
    },
    {
      id: 44,
      name: "Necochea",
      province: "Buenos Aires",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 586,
        username: "cjaviigee",
        first_name: "Javier",
        last_name: "García",
        email: "email@email.com",
        location: 44,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 40,
      name: "Pergamino",
      province: "Buenos Aires",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        email: "email@email.com",
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
      },
    },
    {
      id: 16,
      name: "San Nicolás",
      province: "Buenos Aires",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 25,
        username: "martinborda",
        first_name: "Martín",
        last_name: "Borda",
        email: "email@email.com",
        location: 16,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: null,
      },
    },
    {
      id: 21,
      name: "Catamarca",
      province: "Catamarca",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 367,
        username: "licalejandropaez",
        first_name: "Jorge alejandro",
        last_name: "Paez",
        email: "email@email.com",
        location: 21,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 41,
      name: "Resistencia",
      province: "Chaco",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 533,
        username: "jevillalba",
        first_name: "Emanuel",
        last_name: "Villalba",
        email: "email@email.com",
        location: 41,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 24,
      name: "Comodoro Rivadavia",
      province: "Chubut",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 377,
        username: "jseura",
        first_name: "Juan",
        last_name: "Seura",
        email: "email@email.com",
        location: 24,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id193267.png",
      },
    },
    {
      id: 27,
      name: "Puerto Madryn",
      province: "Chubut",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 42,
        username: "carlospel25",
        first_name: "CArlos",
        last_name: "Pellegrini",
        email: "email@email.com",
        location: 27,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id74561.jpg",
      },
    },
    {
      id: 32,
      name: "Trelew",
      province: "Chubut",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 180,
        username: "vir.esquivel",
        first_name: "Virginia",
        last_name: "Esquivel",
        email: "email@email.com",
        location: 32,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 36,
      name: "Paso de los Libres",
      province: "Corrientes",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 77,
        username: "canterofacundo",
        first_name: "Facundo",
        last_name: "Cantero",
        email: "email@email.com",
        location: 36,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: null,
      },
    },
    {
      id: 3,
      name: "Córdoba",
      province: "Córdoba",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 270,
        username: "manurodriguez008",
        first_name: "Manuel",
        last_name: "Rodriguez",
        email: "email@email.com",
        location: 3,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 28,
      name: "Río Cuarto",
      province: "Córdoba",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        email: "email@email.com",
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
      },
    },
    {
      id: 19,
      name: "Villa María",
      province: "Córdoba",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 37,
        username: "martinoddino",
        first_name: "Martin",
        last_name: "Oddino",
        email: "email@email.com",
        location: 19,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id149853.jpg",
      },
    },
    {
      id: 6,
      name: "Colón",
      province: "Entre Ríos",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 30,
        username: "lucascarp1414",
        first_name: "Lucas",
        last_name: "Gregorio",
        email: "email@email.com",
        location: 6,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id170380.png",
      },
    },
    {
      id: 37,
      name: "Concepción del Uruguay",
      province: "Entre Ríos",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        email: "email@email.com",
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
      },
    },
    {
      id: 25,
      name: "Gualeguaychú",
      province: "Entre Ríos",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 91,
        username: "yongar08",
        first_name: "Yonito",
        last_name: "Garcia",
        email: "email@email.com",
        location: 25,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 13,
      name: "Paraná",
      province: "Entre Ríos",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 29,
        username: "ojedajuane",
        first_name: "Juan",
        last_name: "Ojeda",
        email: "email@email.com",
        location: 13,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id171904.jpg",
      },
    },
    {
      id: 5,
      name: "San Salvador de Jujuy",
      province: "Jujuy",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 44,
        username: "pukllay.club",
        first_name: "Augusto",
        last_name: "Pedraza",
        email: "email@email.com",
        location: 5,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id162715.jpg",
      },
    },
    {
      id: 35,
      name: "Santa Rosa",
      province: "La Pampa",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 49,
        username: "alejandroromanosa93",
        first_name: "Alejandro",
        last_name: "Romano",
        email: "email@email.com",
        location: 35,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id184615.png",
      },
    },
    {
      id: 2,
      name: "Mendoza",
      province: "Mendoza",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 26,
        username: "jondoe",
        first_name: "John",
        last_name: "Doe",
        email: "email@email.com",
        location: 2,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id171906.jpg",
      },
    },
    {
      id: 42,
      name: "Posadas",
      province: "Misiones",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 90,
        username: "ivhansilva",
        first_name: "victor ivan",
        last_name: "silva mazuquelles",
        email: "email@email.com",
        location: 42,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 12,
      name: "Neuquén",
      province: "Neuquén",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 215,
        username: "carlacenciarini",
        first_name: "Carla",
        last_name: "Cenciarini",
        email: "email@email.com",
        location: 12,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id181693.jpg",
      },
    },
    {
      id: 23,
      name: "Cipolletti",
      province: "Río Negro",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        email: "email@email.com",
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
      },
    },
    {
      id: 29,
      name: "San Carlos de Bariloche",
      province: "Río Negro",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 189,
        username: "carlos.veniani",
        first_name: "Carlos",
        last_name: "Veniani",
        email: "email@email.com",
        location: 29,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 10,
      name: "Salta",
      province: "Salta",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 34,
        username: "milenkasulekic",
        first_name: "Mara Milenka",
        last_name: "Sulekic",
        email: "email@email.com",
        location: 10,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id182399.jpg",
      },
    },
    {
      id: 30,
      name: "San Juan",
      province: "San Juan",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 66,
        username: "juanreynoso17",
        first_name: "Juan",
        last_name: "Reynoso",
        email: "email@email.com",
        location: 30,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 31,
      name: "San Luis",
      province: "San Luis",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 532,
        username: "emisnare",
        first_name: "Emiliano",
        last_name: "Favini",
        email: "email@email.com",
        location: 31,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 20,
      name: "Capitán Bermúdez",
      province: "Santa Fe",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        email: "email@email.com",
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
      },
    },
    {
      id: 17,
      name: "Esperanza",
      province: "Santa Fe",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 140,
        username: "pablo_rossi_",
        first_name: "Pablo",
        last_name: "Rossi",
        email: "email@email.com",
        location: 17,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 9,
      name: "Rafaela",
      province: "Santa Fe",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 27,
        username: "pablopochettino_prs",
        first_name: "Pablo",
        last_name: "Pochettino",
        email: "email@email.com",
        location: 9,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id170641.jpg",
      },
    },
    {
      id: 4,
      name: "Rosario",
      province: "Santa Fe",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 209,
        username: "mario",
        first_name: "Mario",
        last_name: "Figge",
        email: "email@email.com",
        location: 4,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id98914.jpg",
      },
    },
    {
      id: 33,
      name: "Santa Fe",
      province: "Santa Fe",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 35,
        username: "sanchoagusritvo",
        first_name: "Agustín José",
        last_name: "Sanchez Ritvo",
        email: "email@email.com",
        location: 33,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 43,
      name: "Venado Tuerto",
      province: "Santa Fe",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 585,
        username: "rafaelblancourt",
        first_name: "Rafael",
        last_name: "Blancourt",
        email: "email@email.com",
        location: 43,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 14,
      name: "Santiago del Estero",
      province: "Santiago del Estero",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 38,
        username: "lucio.auhad",
        first_name: "Lucio",
        last_name: "Auhad",
        email: "email@email.com",
        location: 14,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id143570.jpg",
      },
    },
    {
      id: 38,
      name: "Río Grande",
      province: "Tierra del Fuego",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        email: "email@email.com",
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
      },
    },
    {
      id: 45,
      name: "Ushuaia",
      province: "Tierra del Fuego",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 558,
        username: "mauri.galu",
        first_name: "Mauricio",
        last_name: "Galussio",
        email: "email@email.com",
        location: 45,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "N/A",
      },
    },
    {
      id: 7,
      name: "San Miguel de Tucumán",
      province: "Tucumán",
      geolocation: null,
      mandatory_attendance: false,
      referral: {
        id: 41,
        username: "ezequielmusa",
        first_name: "Ezequiel",
        last_name: "Musa",
        email: "email@email.com",
        location: 7,
        phone: "02444444444",
        whatsapp: "02444444444",
        telegram: "telegramexample",
        avatar: "https://cf.geekdo-static.com/avatars/avatar_id170917.jpg",
      },
    },
  ];

  return new Response(JSON.stringify(data), {
    status: 200,
    "Content-Type": "application/json",
  });
}
